# Generated by Django 4.1.3 on 2022-11-06 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kolor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kolor',
                'verbose_name_plural': 'Kolory',
            },
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Marki',
            },
        ),
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('typ', models.CharField(choices=[('Hatchback ', 'Hatchback'), ('Kombi', 'Kombi'), ('Sedan', 'Sedan'), ('Liftback', 'Liftback'), ('SUV ', 'SUV'), ('Crossover', 'Crossover'), ('Coupe/kabriolet/roadster', 'Coupe/kabriolet/roadster')], max_length=50)),
                ('silnik', models.DecimalField(decimal_places=1, max_digits=3)),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('opony', models.CharField(max_length=20)),
                ('skrzynia_biegow', models.CharField(choices=[('automatyczna', 'automatyczna'), ('manualana', 'manualna')], default='manualna', max_length=20)),
                ('moc', models.IntegerField()),
                ('numer_rejestracyjny', models.CharField(max_length=20)),
                ('numer_seryjny', models.CharField(max_length=20)),
                ('liczba_drzwi', models.CharField(choices=[('2', '2'), ('3', '3'), ('5', '5')], default=5, max_length=3)),
                ('cena', models.FloatField()),
                ('data_produkcji', models.DateField(max_length=10)),
                ('rodzaj', models.CharField(choices=[('osobowy', 'Osobowy'), ('ciężarowy', 'Ciężarowy')], default='osobowy', max_length=50)),
                ('opis', models.CharField(max_length=255, null=True)),
                ('paliwo', models.CharField(choices=[('benzyna', 'Benzyna'), ('gaz', 'Gaz'), ('Diesel', 'Diesel'), ('hybryda', 'Hybryda'), ('elektryk', 'Elektryk')], default='benzyna', max_length=50)),
                ('naped', models.CharField(choices=[('przód', 'Przód'), ('tył', 'Tył')], default='przód', max_length=255, null=True)),
                ('rezerwacja', models.BooleanField(default=False)),
                ('data_dodania', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('autor', models.ForeignKey(default='auth.User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kolor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Komis.kolor')),
                ('marka', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='Komis.marka')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auta',
            },
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Komis.samochod')),
                ('liczba', models.PositiveIntegerField(default=0)),
                ('srednia', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Zdjecie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('samochod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Komis.samochod')),
            ],
            options={
                'verbose_name': 'Zdjęcie',
                'verbose_name_plural': 'Zdjęcia',
            },
        ),
    ]
