# Generated by Django 4.1.3 on 2022-11-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Komis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='czyDoWynajecia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='samochod',
            name='czyWynajety',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='samochod',
            name='okresWynajecia',
            field=models.IntegerField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='samochod',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
