# Generated by Django 4.1.3 on 2022-12-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Komis', '0002_samochod_czydowynajecia_samochod_czywynajety_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='czyZatwierdzony',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='samochod',
            name='okresWynajecia',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
