# Generated by Django 4.1.3 on 2022-12-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Komis', '0004_samochod_iloscdnirezerwacji'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='dataRezerwacji',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='samochod',
            name='okresWynajecia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
