# Generated by Django 4.1.3 on 2022-12-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Komis', '0005_samochod_datarezerwacji_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samochod',
            old_name='dataRezerwacji',
            new_name='data_rezerwacji',
        ),
    ]
