# Generated by Django 4.1.3 on 2022-12-04 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Komis', '0006_rename_datarezerwacji_samochod_data_rezerwacji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samochod',
            old_name='iloscDniRezerwacji',
            new_name='ilosc_dni_rezerwacji',
        ),
    ]
