# Generated by Django 4.1.3 on 2022-12-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Komis', '0009_alter_samochod_ilosc_dni_rezerwacji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samochod',
            old_name='czyZatwierdzony',
            new_name='czyWidoczny',
        ),
    ]
