# Generated by Django 4.1.3 on 2022-12-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Komis', '0010_rename_czyzatwierdzony_samochod_czywidoczny'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='kod_silnika',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='samochod',
            name='ilosc_dni_rezerwacji',
            field=models.PositiveSmallIntegerField(blank=True, default=7, null=True),
        ),
    ]
