# Generated by Django 4.1.3 on 2022-12-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Komis', '0012_alter_samochod_marka_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
