# Generated by Django 4.1.3 on 2022-12-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Komis', '0015_kontakt_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='kosztWynajmuZaGodzine',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
