# Generated by Django 4.1.3 on 2022-12-18 14:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Komis', '0016_samochod_kosztwynajmuzagodzine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samochod',
            name='data_dodania',
        ),
        migrations.AddField(
            model_name='samochod',
            name='data_wynajecia',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
